swagger-ui:
  image: swaggerapi/swagger-ui
  container_name: swagger-ui
  ports:
    - 8082:8080
  volumes:
    - ./swagger-config.json:/usr/share/nginx/html/swagger-config.json
    - ./common:/usr/share/nginx/html/common
    - ./backend:/usr/share/nginx/html/backend
    - ./payment:/usr/share/nginx/html/payment
  environment:
    CONFIG_URL: /swagger-config.json