info:
  title: project
  description: project
  termsOfService: www.google.com
  contact:
    email: am.hofney@gmail.com
  license:
    name: license
    url: www.google.com
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: /api/
    description: Backend Service
externalDocs:
  url: www.google.com
  description: Architecture

tags:
  - name: Customer
    description: Customer
    externalDocs:
      description: description
      url: www.google.com
  - name: Transaction
    description: Transaction
    externalDocs:
      description: description
      url: www.google.com

paths:
  /customers:
    $ref: './api/Customers.yml'
  /customer:
    $ref: './api/Customer.yml'
  /transactions:
    $ref: './api/Transactions.yml'
  /transaction:
    $ref: './api/Transaction.yml'
      
components:
  parameters:
    requestId:
      $ref: './parameters/requestId.yml'
    customerId:
      $ref: './parameters/customerId.yml'
    transactionId:
      $ref: './parameters/transactionId.yml'

  schemas:
    Customer:
      $ref: './schemas/Customer.yml'
    Address:
      $ref: './schemas/Address.yml'
    Transaction:
      $ref: './schemas/Transaction.yml'
    TransactionStatus:
      $ref: './schemas/TransactionStatus.yml'
    Response200:
      $ref: './responses/Response200.yml'
    Response400:
      $ref: './responses/Response400.yml'
    Response401:
      $ref: './responses/Response401.yml'
    Response404:
      $ref: './responses/Response404.yml'
    Response405:
      $ref: './responses/Response405.yml'
    Response5xx:
      $ref: './responses/Response5xx.yml'
        
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
